AWSTemplateFormatVersion: 2010-09-09
Description: |
  This is my Cfn template for ec2 with security grup
  
Resources:
MyWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-01c647eace872fc02
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroupIds: 
        - !Ref MySecGrp
      Tags: 
        - Key: Name
          Value: !Sub Osvaldo ${AWS::StackName}
      UserData: 
        Fn::Base64: |
            #! /bin/bash
            yum update -y
            yum install httpd -y
            FOLDER="https://raw.githubusercontent.com/huseyinuyar/kitten/main/static-web"
            cd /var/www/html
            wget ${FOLDER}/index.html
            wget ${FOLDER}/cat0.jpg
            wget ${FOLDER}/cat1.jpg
            wget ${FOLDER}/cat2.jpg
            wget ${FOLDER}/cat3.png
            systemctl start httpd
            systemctl enable httpd

MySecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ssh and http # Required
      GroupName: emresecportfolio
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: env
          Value: dev

Outputs:
  WebSiteURL:
    Description:This output gives the URL of EC2:
    Value: !Sub
      - http://ec2-54-91-117-159.compute-1.amazonaws.com
      - PublicAddress: !GetAtt MyWebServer.PublicDnsName